version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - keeper-network

  migrations:
    image: postgres:latest
    command: sh -c "PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -f /migrations/*.sql"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - server
    networks:
      - keeper-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    depends_on:
      - postgres
    environment:
      DATABASE_DSN: "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB?sslmode=disable"
      CERT_SSL: "cert.crt"
      PRIVATE_KEY_SSL: "private.key"
      PRIVATE_KEY: "private.key"
      ADDRESS_GRPC: "server:3200"
      JWT_SECRET_KEY: "$JWT_SECRET"
    ports:
      - '3200:3200'
    networks:
      - keeper-network
    # entrypoint: ./entrypoint.sh


volumes:
  postgres-data:


networks:
  keeper-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
